apiVersion: v1
kind: Secret
metadata:
  name: APPLICATION_NAME-secret
type: Opaque
data:
  "spring.datasource.username": TVdBTExFVA==
  "spring.datasource.password": c1NuMDBKUVdlZHFKX3B1dDNyVmNYMTk4

---

apiVersion: v1
kind: Service
metadata:
  name: APPLICATION_NAME-service
spec:
  type: LoadBalancer
  ports:
    - port: 5353
      targetPort: 8989
  externalIPs:
    - 172.16.20.52
  selector:
    app: APPLICATION_NAME
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPLICATION_NAME-deployment
  labels:
    environment: Dev-mwallet
spec:
  selector:
    matchLabels:
      app: APPLICATION_NAME
      environment: Dev-mwallet
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: APPLICATION_NAME
        environment: Dev-mwallet
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: APPLICATION_NAME-container
          image: DOCKERIMAGE
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          imagePullPolicy: Always
          volumeMounts:
         #   - name: storage
         #     mountPath: /app-logs/files/
            - name: tz-config
              mountPath: /etc/localtime           
      volumes:
        #- name: storage
        #  persistentVolumeClaim:
        #    claimName: mwallet-logs-volumeclaim
        - name: tz-config
          hostPath:
                  path: /usr/share/zoneinfo/Africa/Nairobi
                  type: File